server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

spring:
  cloud:
    gateway:
      routes:
        - id: first-service
#          uri: http://localhost:8081/
          uri: lb://FIRST-SERVICE
          predicates:
            - Path=/first-service/**
        - id: second-service
#          uri: http://localhost:8082/
          uri: lb://SECOND-SERVICE
          predicates:
            - Path=/second-service/**
          filters:
            - AddRequestHeader=second-request, second-request-header
            - AddResponseHeader=second-response, second-response-header