server:
  port: 8082

spring:
  application:
    name: client
  profiles:
    active: local
  config:
    import: optional:configserver:http://localhost:8081

management:
  endpoints:
    web:
      exposure:
        include: refresh